services:
  web:
    build:
      context: .
    container_name: django_web
    command: gunicorn --bind 0.0.0.0:8000 large_json_handler.wsgi:application
    volumes:
      - static_volume:/app/staticfiles/
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles/
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  static_volume: